export const BOOTSTRAP_STATE = 'BOOTSTRAP_STATE';
export const SET_IS_DRAGGING = 'SET_IS_DRAGGING';
export const SET_OPTIONS_PANEL_OPEN = 'SET_OPTIONS_PANEL_OPEN';
export const SET_SELECTED_INDEX = 'SET_SELECTED_INDEX';
